language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
cache: pip
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_cebf25e6c525_key
  -iv $encrypted_cebf25e6c525_iv -in .env.enc -out .env -d || true'
- npm install npm@latest -g
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
install:
- pip3 install tox-travis
before_script:
- pip3 install -r requirements.txt
- pip3 install -r requirements-dev.txt
- pip3 install --editable .
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
